# cSpell Settings

# Version of the setting file.  Always 0.2
version: '0.2'
# language - current active spelling language
language: 'en-GB'
# words - list of words to be always considered correct
words:
  - 'githubusercontent'
# ignorePaths - list of globs to ignore file paths
# ignorePaths:
# ignoreWords - list of words to ignore
# ignoreWords:
# flagWords - list of words to be always considered incorrect
# This is useful for offensive words and common spelling errors.
# For example "hte" should be "the"
# flagWords:
